ssrs.datasource.postgres.url=
ssrs.datasource.postgres.username=
ssrs.datasource.postgres.password=

server.contextPath=/
server.port=8443
server.port.http=8080
server.ssl.key-alias=
server.ssl.key-store-password=
server.ssl.key-store=classpath:jks/ssrs-dev-server.jks
server.ssl.key-store-provider=SUN
server.ssl.key-store-type=JKS
server.cors.allowedOrigin=https://localhost:4200/

logging.level.root=info
logging.level.org.springframework.web=debug
logging.level.org.springframework.security=debug

server.error.include-exception = true
server.error.include-message = always
server.error.include-stacktrace = always

ssrs.learning.initialLearningDelaySec = 60
ssrs.learning.nearMissCorrectLearningDelaySec = 86400
ssrs.learning.standardIncorrectBoost = 2
ssrs.learning.nearMissBoost = 3

ssrs.review.futureEventAllowedRatio = .8
ssrs.review.testBaseTimeSec = 15
ssrs.review.testAdditionalTimePerChar = 2

ssrs.maintenance.purgeAfterDays = 7

server.jwt.secret =
server.jwt.cookieExpirySec = 86400
server.jwt.tokenCookieName = accessToken-dev
server.jwt.displayNameCookieName = userDisplayName-dev

# If using Cognito, then Cognito will also have its own password requirement config. This regex should be at least as restrictive as the Cognito config
ssrs.auth.validation.regex = ^(?=.*[a-z])[a-zA-Z0-9!@#$%^&*()+\\-=,._`~\\[\\]{}|;:<>?]{6,64}$
ssrs.auth.validation.message = Password must be at least 6 characters long and must only contain letters, numbers, or any of the following symbols: !@#$%^&*()+-=,._`~[]{}|;:<>?

ssrs.security.allowUserRegistration = true

aws.dynamodb.events.deleteAfterDays = 1
aws.dynamodb.reviews.deleteAfterDays = 1
aws.dynamodb.maxWriteBatchSize = 25

### The following settings are either set into lambda environment variables or unneeded when running inside the lambda (permissions are managed by a role)
### However, if running in build-aws-local mode, all the following need to be set for the service to run
#aws.region = us-west-2
#aws.s3.username =
#aws.s3.key =
#aws.s3.imageBucketName =
#aws.s3.audioBucketName =

#aws.dynamodb.username =
#aws.dynamodb.key =

#aws.cognito.clientId =
#aws.cognito.userPoolId =
#aws.cognito.client.username =
#aws.cognito.client.key =