package com.gt.ssrs.conf.aws;

import com.gt.ssrs.blob.BlobDao;
import com.gt.ssrs.blob.aws.BlobDaoS3;
import com.gt.ssrs.lexicon.LexiconDao;
import com.gt.ssrs.notepad.UserNotepadDao;
import com.gt.ssrs.notepad.aws.UserNotepadDaoDDB;
import com.gt.ssrs.reviewSession.ReviewEventDao;
import com.gt.ssrs.reviewSession.ScheduledReviewDao;
import com.gt.ssrs.reviewSession.aws.ReviewEventDaoDDB;
import com.gt.ssrs.reviewSession.aws.ScheduledReviewDaoDDB;
import com.gt.ssrs.userconfig.UserConfigDao;
import com.gt.ssrs.userconfig.aws.UserConfigDaoDDB;
import com.gt.ssrs.word.WordDao;
import com.gt.ssrs.lexicon.aws.LexiconDaoDDB;
import com.gt.ssrs.word.aws.WordDaoDDB;
import com.gt.ssrs.reviewHistory.WordReviewHistoryDao;
import com.gt.ssrs.reviewHistory.aws.WordReviewHistoryDaoDDB;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.cognitoidentityprovider.CognitoIdentityProviderClient;
import software.amazon.awssdk.services.cognitoidentityprovider.CognitoIdentityProviderClientBuilder;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.DynamoDbClientBuilder;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.S3ClientBuilder;
import software.amazon.awssdk.services.s3.presigner.S3Presigner;

import java.util.List;

@Configuration
public class BeanConfig {

    @Bean
    public S3Client s3Client(@Value("${aws.region}") String region,
                             @Value("${aws.s3.username:}") String s3user,
                             @Value("${aws.s3.key:}") String s3key) {

        S3ClientBuilder s3ClientBuilder = S3Client.builder()
                .region(Region.of(region));

        if (!s3user.isBlank() && !s3key.isBlank()) {
            s3ClientBuilder.credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(s3user, s3key)));
        }

        return s3ClientBuilder.build();
    }

    @Bean
    public S3Presigner s3Presigner(@Value("${aws.region}") String region,
                                   @Value("${aws.s3.username:}") String s3user,
                                   @Value("${aws.s3.key:}") String s3key) {
        S3Presigner.Builder s3PresignerBuilder = S3Presigner.builder()
                .region(Region.of(region));

        if (!s3user.isBlank() && !s3key.isBlank()) {
            s3PresignerBuilder.credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(s3user, s3key)));
        }

        return s3PresignerBuilder.build();
    }

    @Bean
    public DynamoDbClient dynamoDbClient(@Value("${aws.region}") String region,
                                         @Value("${aws.dynamodb.username:}") String dynamodbUser,
                                         @Value("${aws.dynamodb.key:}") String dynamodbKey) {
        DynamoDbClientBuilder dynamoDbClientBuilder = DynamoDbClient.builder()
                .region(Region.of(region));

        if (!dynamodbUser.isBlank() && !dynamodbKey.isBlank()) {
            dynamoDbClientBuilder.credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(dynamodbUser, dynamodbKey)));
        }

        return dynamoDbClientBuilder.build();
    }

    @Bean
    public DynamoDbEnhancedClient dynamoDbEnhancedClient(DynamoDbClient dynamoDbClient) {
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(dynamoDbClient)
                .build();
    }

    @Bean
    public CognitoIdentityProviderClient cognitoIdentityProviderClient(@Value("${aws.region}") String region,
                                                                       @Value("${aws.cognito.client.username:}") String cognitoUsername,
                                                                       @Value("${aws.cognito.client.key:}") String cognitoKey) {

        CognitoIdentityProviderClientBuilder cognitoIdentityProviderClientBuilder = CognitoIdentityProviderClient.builder()
                .region(Region.of(region));

        if (!cognitoUsername.isBlank() && !cognitoKey.isBlank()) {
            cognitoIdentityProviderClientBuilder.credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(cognitoUsername, cognitoKey)));
        }

        return cognitoIdentityProviderClientBuilder.build();
    }
}